name: Saludo usando variables y secretos
run-name: ¡Estoy aprendiendo a usar Variables y Secretos!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo variable
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Hoy es ${{ env.DIA_DE_SEMANA }}!"
        saludo-secretos:
        runs-on: ubuntu-latest
        steps:
        - name: Saludo secretos
                run: echo "$SALUDO, ${{vars.NOMBRE}}. tu contraseña es ${{ secrets.CONTRASENA }}!"
